### ISSUE TITLE
All Python 3 builds are failing

### ISSUE THREAD

**Issue by jugmac00** [zopefoundation/zc.recipe.testrunner#5]
https://travis-ci.com/zopefoundation/zc.recipe.testrunner/builds/133189475

I wonder how this ever worked cf #2 #3

**Comment by mgedmin** [comment]
I suspect this broke with zope.testrunner 4.8.0 which enabled deprecation warnings by default.

**Comment by mgedmin** [comment]
Ah, no, we have a [successful test run using zope.testrunner 5.0](https://travis-ci.com/zopefoundation/zc.recipe.testrunner/jobs/199198117).  Curious.
